# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL5驱动：com.mysql.jdbc.Driver，MYSQL5.8+ 驱动：com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
    #性能分析插件
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: zouyaowen@#123
    connection-init-sqls: set names utf8mb4
    #连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
    lettuce:
      pool:
        #max-active在新版本中max-maxTotal
        max-maxTotal: 32
        #max-wait在新版本中max-maxWaitMillis
        max-maxWaitMillis: 300ms
        max-idle: 16
        min-idle: 8


#MyBatis-Plus配置
mybatis-plus:
  mapperLocations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.zou.learning.entity
  global-config:
    db-config:
      # 主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 数据库类型
      db-type: MYSQL
      # 逻辑删除配置（逻辑删除字段不能更新）
      logic-delete-field: valid
      logic-delete-value: 0
      logic-not-delete-value: 1
      #配置表前缀：如果实体名与表名不一致，配置前缀没有，需要在实体上配置实际表名，使用@TableName注解
      table-prefix: t_
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#开启mybatis的sql日志
logging:
  level:
    com.zou.learning.dao: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

xxl:
  address: http://120.27.2.221:8888/xxl-job
  appName: zouyaowen
  ip:
  port: 19995
  accessToken:
  logPath: /work/logs/xxl-job/jobHandler
  logRetentionDays: -1
